### ISSUE TITLE
Ambiguous occurrence 'defaultTimeLocale'

### ISSUE THREAD

**Issue by joelteon** [kazu-yamamoto/unix-time#30]
When building with GHC 7.10.1 RC1:

```
Preprocessing test suite 'spec' for unix-time-0.3.4...
[1 of 2] Compiling UnixTimeSpec     ( test/UnixTimeSpec.hs, dist/build/spec/spec-tmp/UnixTimeSpec.dyn_o )

test/UnixTimeSpec.hs:62:48:
    Ambiguous occurrence ‘defaultTimeLocale’
    It could refer to either ‘Data.Time.defaultTimeLocale’,
                             imported from ‘Data.Time’ at test/UnixTimeSpec.hs:8:1-16
                             (and originally defined in ‘time-1.5.0.1:Data.Time.Format.Locale’)
                          or ‘System.Locale.defaultTimeLocale’,
                             imported from ‘System.Locale’ at test/UnixTimeSpec.hs:14:23-39
```

**Comment by kazu-yamamoto** [comment]
I cannot check this issue because of https://github.com/haskell/cabal/issues/2375.

Is it OK to merge  #31 and release it without checking tests by myself?

**Comment by kazu-yamamoto** [comment]
Relating to #29.

**Comment by archblob** [comment]
You can just do a `cabal build` with tests enabled and run the test executable from within `dist/spec`.

**Comment by kazu-yamamoto** [comment]
Now unix-time can be build with GHC 7.10. But one test fails. I'm now looking into this.

**Comment by kazu-yamamoto** [comment]
Note that a bug of cabal lib has been fixed. So, I can use a new "cabal" now.

**Comment by kazu-yamamoto** [comment]
Fixed. I have released a new version.

**Comment by pchiusano** [comment]
Hi, @kazu-yamamoto I am running into this problem with the version of unix-time that is in nixpkgs, which looks like unix-time-0.3.4. What is the first released version of unix-time that has the fix?

**Comment by kazu-yamamoto** [comment]
unix-time-0.3.5

In my environment with GHC 7.10.1: 

```
Test suite doctest: RUNNING...
Test suite doctest: PASS
Test suite logged to: dist/test/unix-time-0.3.5-doctest.log
Test suite spec: RUNNING...
Test suite spec: PASS
Test suite logged to: dist/test/unix-time-0.3.5-spec.log
2 of 2 test suites (2 of 2 test cases) passed.
```

**Comment by pchiusano** [comment]
Great, thanks!
