### ISSUE TITLE
unknown symbol `_GLOBAL_OFFSET_TABLE_'

### ISSUE THREAD

**Issue by arno-h** [kazu-yamamoto/unix-time#32]
OS: Debian 8.0, 32Bit (inside VM)
ghc version 7.8.4
cabal-install version 1.20.0.3, using version 1.20.0.2 of the Cabal library

Build.log (everything seems ok):

```
Configuring unix-time-0.3.5...
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking xlocale.h usability... yes
checking xlocale.h presence... yes
checking for xlocale.h... yes
checking for strptime_l... yes
checking for timegm... yes
configure: creating ./config.status
config.status: creating cbits/config.h
Building unix-time-0.3.5...
Preprocessing library unix-time-0.3.5...
[1 of 5] Compiling Data.UnixTime.Types ( dist/build/Data/UnixTime/Types.hs, dist/build/Data/UnixTime/Types.o )
[2 of 5] Compiling Data.UnixTime.Diff ( Data/UnixTime/Diff.hs, dist/build/Data/UnixTime/Diff.o )
[3 of 5] Compiling Data.UnixTime.Sys ( dist/build/Data/UnixTime/Sys.hs, dist/build/Data/UnixTime/Sys.o )
[4 of 5] Compiling Data.UnixTime.Conv ( Data/UnixTime/Conv.hs, dist/build/Data/UnixTime/Conv.o )
[5 of 5] Compiling Data.UnixTime    ( Data/UnixTime.hs, dist/build/Data/UnixTime.o )
In-place registering unix-time-0.3.5...
Creating package registration file: /tmp/pkgConf-unix-time-0.3608.5
Installing library in
/home/user/.cabal/lib/i386-linux-ghc-7.8.4/unix-time-0.3.5
Registering unix-time-0.3.5...
Installed unix-time-0.3.5
```

But when I run e.g. ghc-modi, I get the following error:

```
ghc-modi
check Main.hs
ghc-modi: /home/user/.cabal/lib/i386-linux-ghc-7.8.4/unix-time-0.3.5/libHSunix-time-0.3.5.a: unknown symbol `_GLOBAL_OFFSET_TABLE_'
NG BUG: ghc-modi: unable to load package `unix-time-0.3.5'
```

**Comment by arno-h** [comment]
Adding: this is weird: the above error happens, when I'm inside a yesod project. If I start ghc-modi outside of this project, then it does not complain about the missing symbol but succeeds without error!?
I've deleted dist/ and rebuilt the project, but this does not help. Is there anything else I can do?

**Comment by kazu-yamamoto** [comment]
ghc-mod does not support `.hsc`. You should convert `Data/UnixTime/*.hsc` to `*.hs` by `hsc2hs` by hand.

**Comment by arno-h** [comment]
Thanks. Please ignore my ignorance (I'm still a newbie to Haskell): after I ``cabal install unix-time`` there is no ``*.hsc`` file left in ``~/.cabal/lib/i386-linux-ghc-7.8.4/unix-time-0.3.5``, only ``*.hi`` and ``*.dyn_hi`` files. Does this mean, I should install the package manually so that I can replace *.hsc by *.hs files?

Also, I don't understand the difference a single change of directory (inside yesod cabal project vs. outside cabal project) makes. I understand that ghc-mod is apparently reading my cabal file and then using that information. But why an error in one case and no problem in the other case? E.g. here's the relevant ``strace`` output calling ghc-mod from *outside* the project directory, checking a file from *inside* the project (ghc-mod runs successfully):

```
open("/home/user/.cabal/lib/i386-linux-ghc-7.8.4/unix-time-0.3.5/Data/UnixTime/Diff.hi", O_RDONLY|O_NOCTTY|O_NONBLOCK|O_LARGEFILE) = 3
```

and here is what happens when called from *inside* the project checking the same file (finishes with error):

```
open("/home/user/.cabal/lib/i386-linux-ghc-7.8.4/unix-time-0.3.5/libHSunix-time-0.3.5.a", O_RDONLY|O_LARGEFILE) = 3
ghc-mod: /home/arno/.cabal/lib/i386-linux-ghc-7.8.4/unix-time-0.3.5/libHSunix-time-0.3.5.a: unknown symbol `_GLOBAL_OFFSET_TABLE_'
```

Why is it loading the *.hi file when outside the cabal project and loading the *.a inside the project?

**Comment by kazu-yamamoto** [comment]
Probably, I misunderstood  your explanation. Please show me your `Main.hs` first.
And this is not a problem of `unix-time` but of `ghc-mod`.
