### ISSUE TITLE
Question on Cross Compiling for ARM

### ISSUE THREAD

**Issue by bdoering** [kazu-yamamoto/unix-time#34]
I am currently trying to cross-compile the `scotty-starter` package, which also depends on `unix-time`. I get the following error:

```
Building unix-time-0.3.5...
Preprocessing library unix-time-0.3.5...
Data/UnixTime/Types.hsc:15 directive let cannot be handled in cross-compilation mode
Failed to install unix-time-0.3.5
```

There seems to be just a single `let` statement in the source code, namely:

```
#let alignment t = "%lu", (unsigned long)offsetof(struct {char x__; t (y__); }, y__)
```

I don't quite understand what's going on there, but how could I rewrite this without using a `let` statement?

Thanks!

**Comment by kazu-yamamoto** [comment]
@archblob contributed this code.

@archblob Would you give a look?

**Comment by archblob** [comment]
I'll take a look today when I find some time.

**Comment by bdoering** [comment]
Great, that fixed it. Thanks!

**Comment by kazu-yamamoto** [comment]
@bdoering Sorry for the delay. I was inactive in the last week for private reasons.
