### ISSUE TITLE
Formatting time and parsing time mismatch using %s format

### ISSUE THREAD

**Issue by Ofenhed** [kazu-yamamoto/unix-time#36]
```
Prelude T BS C8> a <- getUnixTime 
Prelude T BS C8> let b = formatUnixTimeGMT (C8.pack "%s") a
Prelude T BS C8> let c = parseUnixTimeGMT (C8.pack "%s") b
Prelude T BS C8> a
UnixTime {utSeconds = 1472983289, utMicroSeconds = 468351}
Prelude T BS C8> b
"1472979689"
Prelude T BS C8> c
UnixTime {utSeconds = 1472986889, utMicroSeconds = 0}

```

**Comment by archblob** [comment]
Yeah, you are right, ``formatUnxiTimeGMT`` uses ``strftime*`` under the hood.
If we look in the man page for ``strftime*`` we see that ``%s`` will make use of ``mktime``
that make a call to ``tzset()`` and we get local time. This is the difference in a and b.
Probably the same thing is happening with ``parseUnixTimeGMT`` which uses ``strptime*``.

**Comment by Ofenhed** [comment]
That was a quick response. Thank you 👍

**Comment by kazu-yamamoto** [comment]
If I understand correctly,  43c2e1b should pass the test case above but not.
@archblob Could you tell me reasons?

**Comment by Ofenhed** [comment]
@kazu-yamamoto If I understand the test input data correctly it may have any value set for nanoseconds, which will be set to 0 by the parsed value, thus failing the comparison.

**Comment by archblob** [comment]
@kazu-yamamoto As @Ofenhed mentioned, part of the story is that ``utMicroSeconds`` is always set to 0 when parsing. The formatting function also ignores this information. So the equality only works up to useconds. The C code uses ``gmtime_r`` and ``timegm`` and they work with ``time_t``, that's why we drop the useconds.

**Comment by archblob** [comment]
Maybe we should mention this in the documentation for both functions. The format function should warn that utMicroSeconds are ignored and the parse function that utMicroSeconds will always be 0.

**Comment by kazu-yamamoto** [comment]
I have written warnings.

**Comment by kazu-yamamoto** [comment]
A new version has been released.
