### ISSUE TITLE
Proposal for windows support

### ISSUE THREAD

**Issue by sighingnow** [kazu-yamamoto/unix-time#43]
Hi, @kazu-yamamoto,

The package-time is awesome and used by many mainstream packages in haskell community. However the windows platform (mingw) is not supported, mainly due to the lack of `strptime` function. (other things like `gmtime_r` and `localtime_r` have the equivalents, `gmtime_s` and `localtime_s`).

The package has the name **unix-** time so its fine to support *nix system only. This package is used by many useful packages (such as tinylog), causing these packages can't be used on windows, too. It's bad to suffer such compatibility issue due to the lack of `strptime`. This function is not so-much platform-dependent.

There's already some effort by others to port the openbsd version of `strptime` to windows [[ref 1]](https://github.com/Alexpux/MINGW-packages/blob/master/mingw-w64-libkml/strptime.c). This file is also licensed with BSD, which is fine to integrate it into unix-time. If you are +1 for this proposal, I'm volunteer to submit such a patch for it !

1: https://github.com/Alexpux/MINGW-packages/blob/master/mingw-w64-libkml/strptime.c

**Comment by kazu-yamamoto** [comment]
> The package-time is awesome

Did you mean "unix-time"?

Anyway, it would be very nice to support Windows. PR is highly welcome!

**Comment by sighingnow** [comment]
> Did you mean "unix-time"?

It must be a typo. I did want to write `The package unix-time`..

> PR is highly welcome!

PR is coming soon!

**Comment by kazu-yamamoto** [comment]
Ping @sighingnow

**Comment by sighingnow** [comment]
Thanks for patience @kazu-yamamoto .

I have added an implementation of `strptime` to this package, and fix windows related issues about the struct `timeval`. But I'm still stuck at the `strftime` function, mainly about the `%s`, `%z` and `%Z` flags. I haven't found an easy and clean way to fix it.

Anyway I'll submit a pull request tonight.

**Comment by sighingnow** [comment]
Closed as we already have #44 .
