### ISSUE TITLE
Build failure due to cabal-doctest not installed

### ISSUE THREAD

**Issue by pepeiborra** [kazu-yamamoto/unix-time#50]
`Setup.hs` no longer goes through autoconf:

https://github.com/kazu-yamamoto/unix-time/blob/6bf3d9ba7834e98f4c0d70646698b41d7692c314/Setup.hs#L30-L32

**Comment by pepeiborra** [comment]
Moreover, the `Setup.hs` CPP conditionals don't work for `runghc Setup.hs configure`

**Comment by kazu-yamamoto** [comment]
81aeacad74f6cab880e8172333a803add7540aee should fix the first one.

> Moreover, the `Setup.hs` CPP conditionals don't work for `runghc Setup.hs configure`

I have no idea on how to fix this. Is this important?

**Comment by kazu-yamamoto** [comment]
We can fix this like this: https://github.com/haskell/network/pull/365

**Comment by kazu-yamamoto** [comment]
This is fixed in a new version.
